import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://demoqa.com/")
    page.locator("div").filter(has_text=re.compile(r"^Forms$")).first.click()
    page.get_by_text("Forms").click()
    page.locator("span").filter(has_text="Elements").locator("div").first.click()
    page.get_by_text("Text Box").click()
    page.get_by_role("textbox", name="Full Name").click()
    page.get_by_role("textbox", name="Full Name").fill("Aurgha Das")
    page.get_by_role("textbox", name="name@example.com").click()
    page.get_by_role("textbox", name="name@example.com").fill("aurghadas04@gmail.com")
    page.get_by_role("textbox", name="Current Address").click()
    page.get_by_role("textbox", name="Current Address").fill("Uttara, Dhaka")
    page.locator("#permanentAddress").click(modifiers=["Shift"])
    page.locator("#permanentAddress").click()
    page.locator("#permanentAddress").fill("Barishal, Bangladesh")
    page.locator(".col-12 > div:nth-child(4)").click()
    page.get_by_text("Radio Button").click()
    page.get_by_text("Impressive").click()
    page.get_by_text("Check Box").click()
    page.locator("#tree-node").get_by_role("img").nth(3).click()
    page.get_by_text("Web Tables").click()
    page.get_by_text("Buttons").click()
    page.get_by_role("button", name="Double Click Me").dblclick()
    page.get_by_role("button", name="Right Click Me").click()
    page.get_by_role("button", name="Click Me", exact=True).click()
    page.get_by_role("button", name="Right Click Me").click(button="right")
    page.get_by_role("listitem").filter(has_text=re.compile(r"^Links$")).click()
    page.get_by_role("listitem").filter(has_text="Broken Links - Images").click()
    page.get_by_text("Upload and Download").click()
    page.get_by_text("Dynamic Properties").click()
